version: '3'

services:
  shop_back:
    image: shop_back
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - .env:/.env
    