# Generated by Django 4.2.19 on 2025-04-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ai_for_clients",
                    models.BooleanField(
                        default=False, help_text="Enable AI responses for non-staff users' chats"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Settings",
                "verbose_name_plural": "Chat Settings",
            },
        ),
    ]
