# Generated by Django 4.2.19 on 2025-04-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_guestuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_chatbot",
            field=models.BooleanField(default=False),
        ),
    ]
