name: build-push-and-deploy1

on:
  push:
    branches:
      - 'main'

jobs:
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         push: true
  #         tags: allania7med11/shop_back:latest
  deploy:
    # needs: docker
    runs-on: ubuntu-latest
    env:
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_IP_ADDRESS: ${{ secrets.DEPLOY_IP_ADDRESS }}
      ENV_FILE_CONTENTS: ${{ secrets.ENV_FILE_CONTENTS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Create shop_back directory
        run: mkdir -p ~/shop_back/
  
      - name: Get the contents of .env secret
        run: echo "$ENV_FILE_CONTENTS" > ~/shop_back/.env
      
      - name: Test connection
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.DEPLOY_IP_ADDRESS }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connection test successful"
      
      # - name: Upload file via SSH
      #   uses: nicklasfrahm/scp-action@main
      #   with:
      #     direction: upload
      #     host: ${{ secrets.DEPLOY_IP_ADDRESS }}
      #     username: ${{ secrets.DEPLOY_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: |
      #       ~/shop_back/.env
      #     target: ~/shop_back/
  
      - name: SSH into droplet and run Docker commands
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.DEPLOY_IP_ADDRESS }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull allania7med11/shop_back:latest
            docker run -d --network=host --env-file ~/shop_back/.env --restart unless-stopped allania7med11/shop_back:latest