# Generated by Django 4.0.5 on 2023-02-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description'),
        ('products', '0002_product_slug_alter_category_name_alter_category_slug'),
    ]

    operations = [
    ]
