# Generated by Django 4.0.5 on 2023-10-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0006_alter_order_total_amount_alter_orderitems_subtotal",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderitems",
            unique_together={("order", "product")},
        ),
    ]
