# Generated by Django 4.0.5 on 2023-10-21 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_orderitems_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
