# Generated by Django 4.0.5 on 2025-02-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_order_created_at_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
